import { Restaurant, User } from '@/types';

// Default Center Coordinates: San Francisco Downtown (37.7749, -122.4194)
export const DEFAULT_CENTER_LOCATION = {
  lat: 37.7749,
  lng: -122.4194,
  address: 'Market Street, San Francisco, CA',
  city: 'San Francisco',
  isLiveGps: false,
};

export const MOCK_RESTAURANTS: Restaurant[] = [
  {
    id: 'rest-1',
    name: 'Osteria Del Bella',
    tagline: 'Artisanal Neapolitan Pizza & Handmade Pasta',
    description: 'Authentic wood-fired Neapolitan pizzas, handmade tagliatelle, and curated Italian wines in a warm rustic setting.',
    cuisine: ['Italian', 'Pizza', 'Pasta'],
    priceLevel: '$$',
    rating: 4.8,
    reviewCount: 342,
    address: '450 Sutter St, San Francisco, CA',
    location: { lat: 37.7891, lng: -122.4082 },
    distanceKm: 0.8,
    phone: '+1 (415) 555-0192',
    website: 'https://osteriadelbella.example.com',
    imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1579684947550-22e945225d9a?auto=format&fit=crop&w=800&q=80',
    ],
    isOpenNow: true,
    openingHours: '11:30 AM - 10:00 PM',
    features: {
      hasOutdoorSeating: true,
      isVegetarianFriendly: true,
      isFamilyFriendly: true,
      hasParking: false,
      isGlutenFree: true,
    },
    popularDishes: [
      { id: 'd-1', name: 'Margherita DOC', price: 19.5, description: 'San Marzano tomatoes, fresh buffalo mozzarella, basil', isPopular: true },
      { id: 'd-2', name: 'Truffle Tagliatelle', price: 26.0, description: 'Handmade pasta with black truffle cream sauce', isPopular: true },
    ],
    reviews: [
      { id: 'r-1', authorName: 'Elena Rostova', rating: 5, date: '2 days ago', comment: 'Best pizza in the city! The crust is so airy and delicious.' },
    ],
  },
  {
    id: 'rest-2',
    name: 'Sakura Omakase & Sushi Bar',
    tagline: 'Precision Edomae Sushi & Craft Sake',
    description: 'Master chef crafted sushi using sustainably caught wild fish flown in daily from Tokyo fish markets.',
    cuisine: ['Japanese', 'Sushi', 'Asian'],
    priceLevel: '$$$$',
    rating: 4.9,
    reviewCount: 512,
    address: '220 Bush St, San Francisco, CA',
    location: { lat: 37.7908, lng: -122.4035 },
    distanceKm: 1.2,
    phone: '+1 (415) 555-0821',
    website: 'https://sakuraomakase.example.com',
    imageUrl: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1611143669185-af224c5e3252?auto=format&fit=crop&w=800&q=80',
    ],
    isOpenNow: true,
    openingHours: '5:00 PM - 10:30 PM',
    features: {
      hasOutdoorSeating: false,
      isVegetarianFriendly: false,
      isFamilyFriendly: false,
      hasParking: true,
    },
    popularDishes: [
      { id: 'd-3', name: '12-Piece Chef Omakase', price: 95.0, description: 'Seasonal selection of premium nigiri and hand rolls', isPopular: true },
      { id: 'd-4', name: 'Bluefin Otoro Nigiri', price: 16.0, description: 'Seared fatty tuna with truffle soy glaze', isPopular: true },
    ],
    reviews: [
      { id: 'r-2', authorName: 'Marcus Vance', rating: 5, date: '1 week ago', comment: 'An extraordinary omakase journey. Pure melt-in-mouth quality.' },
    ],
  },
  {
    id: 'rest-3',
    name: 'Saffron & Cardamom Indian Kitchen',
    tagline: 'Modern Indian Gastronomy & Clay Oven Delicacies',
    description: 'Vibrant regional Indian curries, tandoori grills, and freshly baked garlic naans spiced with authentic hand-ground seasonings.',
    cuisine: ['Indian', 'Curry', 'Asian'],
    priceLevel: '$$',
    rating: 4.7,
    reviewCount: 289,
    address: '88 5th St, San Francisco, CA',
    location: { lat: 37.7824, lng: -122.4069 },
    distanceKm: 0.6,
    phone: '+1 (415) 555-0453',
    website: 'https://saffroncardamom.example.com',
    imageUrl: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=800&q=80',
    ],
    isOpenNow: true,
    openingHours: '11:00 AM - 10:00 PM',
    features: {
      hasOutdoorSeating: true,
      isVegetarianFriendly: true,
      isFamilyFriendly: true,
      hasParking: false,
      isHalal: true,
      isGlutenFree: true,
    },
    popularDishes: [
      { id: 'd-5', name: 'Slow-Cooked Butter Chicken', price: 21.0, description: 'Tender chicken in rich tomato cream sauce', isPopular: true },
      { id: 'd-6', name: 'Paneer Tikka Masala', price: 19.5, description: 'Chargrilled cottage cheese in spiced gravy', isPopular: true },
    ],
    reviews: [
      { id: 'r-3', authorName: 'Priya Sharma', rating: 5, date: '3 days ago', comment: 'Authentic flavors and generous portions. The garlic naan is unbelievable!' },
    ],
  },
  {
    id: 'rest-4',
    name: 'El Verde Taqueria & Mezcal Bar',
    tagline: 'Farm-to-Table Mexican Street Food',
    description: 'Slow-braised birria tacos, house-made corn tortillas, and craft cocktail mezcal creations.',
    cuisine: ['Mexican', 'Tacos', 'Latin'],
    priceLevel: '$',
    rating: 4.6,
    reviewCount: 620,
    address: '610 Mission St, San Francisco, CA',
    location: { lat: 37.7876, lng: -122.4011 },
    distanceKm: 1.4,
    phone: '+1 (415) 555-0912',
    website: 'https://elverdetaqueria.example.com',
    imageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=800&q=80',
    ],
    isOpenNow: true,
    openingHours: '10:30 AM - 11:00 PM',
    features: {
      hasOutdoorSeating: true,
      isVegetarianFriendly: true,
      isFamilyFriendly: true,
      hasParking: true,
      isGlutenFree: true,
    },
    popularDishes: [
      { id: 'd-7', name: 'Quesabirria Tacos (3x)', price: 16.0, description: 'Crispy cheese birria tacos served with consommé broth', isPopular: true },
    ],
    reviews: [
      { id: 'r-4', authorName: 'Carlos Gomez', rating: 5, date: 'Yesterday', comment: 'Hands down the best birria tacos in town!' },
    ],
  },
  {
    id: 'rest-5',
    name: 'Green Earth Bistro & Juice Lounge',
    tagline: '100% Organic Plant-Based Fine Dining',
    description: 'Wholesome organic grain bowls, cold-pressed juices, and decadent vegan desserts prepared with locally sourced produce.',
    cuisine: ['Vegan', 'Healthy', 'Salads'],
    priceLevel: '$$',
    rating: 4.8,
    reviewCount: 198,
    address: '312 Valencia St, San Francisco, CA',
    location: { lat: 37.7692, lng: -122.4218 },
    distanceKm: 2.1,
    phone: '+1 (415) 555-0311',
    website: 'https://greenearthbistro.example.com',
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80',
    ],
    isOpenNow: true,
    openingHours: '8:00 AM - 8:00 PM',
    features: {
      hasOutdoorSeating: true,
      isVegetarianFriendly: true,
      isFamilyFriendly: true,
      hasParking: false,
      isGlutenFree: true,
    },
    popularDishes: [
      { id: 'd-8', name: 'Golden Turmeric Grain Bowl', price: 17.5, description: 'Quinoa, roasted sweet potato, avocado, and tahini drizzle', isPopular: true },
    ],
    reviews: [
      { id: 'r-5', authorName: 'Samantha Green', rating: 5, date: '4 days ago', comment: 'Refreshing, healthy, and incredibly filling!' },
    ],
  },
];

export const MOCK_USER: User = {
  id: 'usr-1',
  email: 'anand.engineer@gourmetai.io',
  name: 'Anand Raj',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
  preferences: {
    preferredCuisines: ['Italian', 'Japanese', 'Indian'],
    budgetRange: ['$', '$$', '$$$'],
    defaultRadiusKm: 3.0,
    dietaryRestrictions: ['Vegetarian Friendly'],
    autoDetectLocation: true,
  },
};
